version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    restart: on-failure
    volumes:
      - ./:/usr/src/app
    restart: on-failure
    environment:
      - NODE_PORT=3000
      - NODE_HOST=0.0.0.0
